### ISSUE TITLE
iOS Scene Issue With Dimmed Lights

### ISSUE THREAD

**Issue by Sinandgrin** [jvmahon/Homebridge-HomeSeer4#45] opened 2020-01-31 13:23 UTC
Looks like even after I upgraded to 0.0.42 I am still having an issue with scenes setting all my lights correctly. I built a new scene in Homekit that sets 8 insteon lights that are controlled through Homeseer all to different Dim values and I am having issues either where the lights are quickly coming on full to 100% and then dimming down to the value they should be at, or they stay on at 100% and do not match the scene's Dim setting. I feel that is the important part for my issue. When I create a scene that sets lights to either 100% or 0% (On, Off) things work just fine now (which was not the case before version 0.0.42). 

The below terminal log shows devices highlighted in yellow that come on first to 100% and then a second or so later dim back down to the desired value and devices in blue that only came on to 100% and never reset back to the 50% value they should have. 
 
![image](https://user-images.githubusercontent.com/5924175/73542431-ae1d4a80-4402-11ea-9022-3e3714a19e36.png)

I built this scene using the stock Apple Home app, adding the device and setting a dim value.

**Comment by jvmahon** [comment] 2020-01-31 13:54
I may have to try and develop some custom handling code for insteon. It shouldn't take that long to develop that, but I'll need your input to do it.

Some info. I'll need to get started
1)  A copy of your config.json file
2) An image of the "status graphics" page for your insteon light #248 and for light #128.
3) Which plugin are you using?
4) Execute the following 4 function and then cut/paste the output into a file (substitute the IP of your HomeSeer system in place of 127.0.0.1):
`````
http://127.0.0.1/JSON?request=getStatus&ref=248

http://127.0.0.1/JSON?request=getControl&ref=248

http://127.0.0.1/JSON?request=getStatus&ref=128

http://127.0.0.1/JSON?request=getControl&ref=128
`````

**Comment by Sinandgrin** [comment] 2020-01-31 14:14
Sure, glad to help and provide this information. I can plan to get you this later today when I return home from work. 

In the meantime, I'd like to point out that when I was using your previous Homebridge 2018 plugin, I didn't seem to have this issue. I don't know if there was different handling in that plugin or if something changed with iOS 13.3.1 which I upgraded to on some of my devices (note I did not upgrade my iPad and Apple TV yet which are my Homekit hubs).

**Comment by jvmahon** [comment] 2020-01-31 15:23
Thanks. Yes, there were some changes in handling the "On" and "Alternate On" values that HomeSeer uses. The plugin now queries HomeSeer to figure out what these are. However, I'm finding that some non-HomeSeer plugins didn't use this information consistently, but its usually an easy fix to get the working. The information I asked for lets me see if your plugin is doing something "unusual" from what is expected.

**Comment by jvmahon** [comment] 2020-01-31 19:25
And just wondering -  I thought Insteon supports direct pairing to HomeKit - why bother with the plugin (unless you have an older Insteon hub)?

**Comment by Sinandgrin** [comment] 2020-02-01 01:55
Ok here is the information that you requested. Note, for the config.json file I only included the relevant data for the homebridge plugin and stripped out other plugin and server information out of privacy. Let me know if you must have this and I can add some of it back.

[Issue 45 Support.zip](https://github.com/jvmahon/Homebridge-HomeSeer4/files/4142045/Issue.45.Support.zip)

As for your question about native HomeKit support, no I run a Homeseer 3 Pro system on a windows machine, connected to an Insteon USB PLM (2413U) https://www.smarthome.com/powerlinc-modem-insteon-2413u-usb-interface-dual-band.html. This setup does not offer any native HomeKit integration. 

I do know that an older standalone Insteon hub (Insteon Hub (HomeKit-enabled)2243-222) did have some native homekit support but it was  limited and a less powerful setup compared to HS3 Pro and the USB PLM. 

Let me know if you need any other information.

**Comment by jvmahon** [comment] 2020-02-01 05:45
Thanks. This was helpful. One thing I noticed is that Insteon doesn't seem to have a "last value" turn-on ability. That is, in Z-Wave, if you tap an icon to turn on the light, it goes to whatever the last value of the light was. For your Insteon dimmers, it seems like lights always turn on to 100% - is that correct?  I think I can fix the scene issue while also setting the Insteon lights so that a single-tap on a dimmer icon turns them to their last value rather than 100% - would that make sense?

**Comment by jvmahon** [comment] 2020-02-01 14:26
@Sinandgrin  
I have a fix, but it needs testing. If you want to give it a try, you can install the fix using:
`````
npm -g install git://github.com/jvmahon/homebridge-homeseer4#scene-fix
`````

**Comment by Sinandgrin** [comment] 2020-02-01 21:15
> @Sinandgrin
> I have a fix, but it needs testing. If you want to give it a try, you can install the fix using:
> 
> ```
> npm -g install git://github.com/jvmahon/homebridge-homeseer4#scene-fix
> ```

I think that fixed it! I am running HOOBS at the moment so I had to figure out how to manually install this branch of your Homeseer4 plugin, but I think I got it sorted out, setup my devices and a new scene with multiple Dim values for 10 devices and everything seems to work properly now. 

Is there anything else you need or want me to test before you merge and promote this to the main branch?

**Comment by jvmahon** [comment] 2020-02-01 21:33
Just run it for the next day and I'll merge on Sunday if neither of us has a problem. I'll post here once I've merged.

**Comment by Sinandgrin** [comment] 2020-02-01 21:51
That works. Thanks so much for your help in quickly resolving this!

**Comment by Sinandgrin** [comment] 2020-02-02 17:11
Looks like you already merged this branch but I did want to point out some new behavior that I noticed that I think you may have introduced on purpose based on your "last value" comment above.

I now notice that when I select an off device to turn on from the HomeKit app, that it turns on to the last value that device was set on to, which is not how I experience behavior with other non-insteaon lights/devices in HomeKit. 

Since you asked, the Homeseer Insteon plugin I am using, does have an operating flag to set whether or not you desire this behavior (see image below). Would it be possible for your plugin to read this homeseer device parameter and act then based on that flag, or introduce a new parameter in the config.json file to set (on/off) this resume last value behavior? 

If neither are options, I would like to request a change so that this was not the current behavior. I prefer to have the device turn on to 100% when it is clicked from an off state. If I want to turn it on to a dimmed value when it is off, I'll press and hold to bring up the slider and set the desired dim value that way.

Just curious to see what you think is possible here.

![image](https://user-images.githubusercontent.com/5924175/73611853-5cb4bd00-45b4-11ea-8cde-9adfd05b94df.png)

**Comment by jvmahon** [comment] 2020-02-02 18:08
I believe that the proper behavior in HomeKit is that a tap on the icon should bring the light to its "last" value.  I say this because when a HomeKit icon is tapped it actually sends its last value to the plugin - that's an inherent HomeKit behavior. Previously, the plugin would ignore this and just use the Z-Wave last value or Hue last value by sending a "255" as the on value (As you pointed out, Insteon didn't support the last value). But as was pointed out, when I handled it using the set to last value ("255") code, scenes didn't set their values properly. So I think that what you are seeing now is the way it should have worked all along).   There is one caveat - when the HomeBridge application is first started, it may not have the proper last value of each light (particularly if the light was change since it was previously turned on) so the first time it does an on / off cycle, I think it may go to 100%. After that point, it should "know" the last values.

As for your suggestion to always turn the lights on to 100%, I think the tradeoff there is if I do that, then scenes may not work properly. I'll check into this some more, but I think the better choice is to have scenes work as intended.

**Comment by Sinandgrin** [comment] 2020-02-02 18:24
Understood. I re-tested with a Hue light and you are right it appears that too will come back on by default to the last dim value. I can live with the change and certainly would rather keep the scenes working now anyways. IF things are just not working for me, then I'll explore options in Homeseer as you suggested. Thanks.

**Comment by jvmahon** [comment] 2020-02-02 18:47
OK, I'm going to close out this issue. If you have any further problems, just re-open.

**Closed by jvmahon** 2020-02-02 18:47 UTC
